### ISSUE TITLE
Clone error

### ISSUE THREAD

**Issue by Spidey2077** [codewithweeb/WeebZone#11]
After recent multi clone push this error is occurred when ever "/clone" command is given to the bot (upstream repo is this repo)

2022-08-15T09:10:06.894990+00:00 app[web.1]: Exception in thread Thread-4 (cloneNode):
2022-08-15T09:10:06.895009+00:00 app[web.1]: Traceback (most recent call last):
2022-08-15T09:10:06.895042+00:00 app[web.1]:   File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
2022-08-15T09:10:06.895404+00:00 app[web.1]:     self.run()
2022-08-15T09:10:06.895418+00:00 app[web.1]:   File "/usr/lib/python3.10/threading.py", line 946, in run
2022-08-15T09:10:06.895595+00:00 app[web.1]:     self._target(*self._args, **self._kwargs)
2022-08-15T09:10:06.895608+00:00 app[web.1]:   File "/usr/src/app/bot/modules/clone.py", line 215, in cloneNode
2022-08-15T09:10:06.895767+00:00 app[web.1]:     _clone(update.message, context.bot)
2022-08-15T09:10:06.895779+00:00 app[web.1]:   File "/usr/src/app/bot/modules/clone.py", line 85, in _clone
2022-08-15T09:10:06.895898+00:00 app[web.1]:     if reply_to is not None:
2022-08-15T09:10:06.896067+00:00 app[web.1]: UnboundLocalError: local variable 'reply_to' referenced before assignment

**Comment by codewithweeb** [comment]
fixed
